# Generated by Django 4.0.6 on 2022-07-27 21:47

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UploadedFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='largefile')),
                ('fiename', models.CharField(max_length=20)),
                ('cutomuser', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='customUser', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Chunks',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('chunk', models.FileField(upload_to='chunks')),
                ('chunksize', models.IntegerField()),
                ('uploadedflie', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='uploadedfile', to='api.uploadedfile')),
            ],
        ),
    ]
