# Generated by Django 4.0.6 on 2022-07-29 00:32

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('api', '0002_remove_uploadedfile_fiename_uploadedfile_filename_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ChunkOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('zip', models.CharField(blank=True, max_length=20, null=True)),
                ('file_name', models.CharField(blank=True, max_length=20, null=True)),
                ('chunk_size', models.IntegerField()),
                ('custom_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='custom_User', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.RemoveField(
            model_name='uploadedfile',
            name='cutomuser',
        ),
        migrations.DeleteModel(
            name='Chunks',
        ),
        migrations.DeleteModel(
            name='UploadedFile',
        ),
    ]
